src/main/java/com/viettel/controller/BaseController.java
package com.viettel.controller;


import com.google.gson.Gson;
import com.viettel.exception.AppException;
import com.viettel.lazy.LazyDataModelBaseNew;
import com.viettel.model.BaseModel;
import com.viettel.model.Customer;
import com.viettel.persistence.CustomerDaoService;
import com.viettel.persistence.GenericDaoImplNewV2;
import com.viettel.util.Import;
import org.apache.commons.io.FilenameUtils;
import org.primefaces.json.JSONArray;
import org.primefaces.json.JSONObject;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.UploadedFile;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public abstract class BaseController<T extends  Serializable>  implements Serializable {
    private UploadedFile uploadedFile;
    public BaseModel obj;
    public LazyDataModel<T> model;
    public GenericDaoImplNewV2<T,Integer>  dao;
    private List<ColumnModel> columns;

    public BaseModel getObj() {
        return obj;
    }

    public void setObj(BaseModel obj) {
        this.obj = obj;
    }

    public LazyDataModel<T> getModel() {
        return model;
    }

    public void setModel(LazyDataModel model) {
        this.model = model;
    }

    public GenericDaoImplNewV2<T,Integer> getDao() {
        return dao;
    }

    public void setDao(GenericDaoImplNewV2 dao) {
        this.dao = dao;
    }

    public List<ColumnModel> getColumns() {
        return columns;
    }

    public void setColumns(List<ColumnModel> columns) {
        this.columns = columns;
    }

    public UploadedFile getUploadedFile() {
        return uploadedFile;
    }

    public void setUploadedFile(UploadedFile uploadedFile) {
        this.uploadedFile = uploadedFile;
    }

    public List<String> getAllTables(){
        List<?> listTable = dao.findListSQLAll("SELECT table_name FROM all_tables\n" +
                "WHERE owner = 'GIANG'");
        List<String> listString = new ArrayList<>();
        for (Object table: listTable) {
            listString.add(table.toString());
        }
        return listString;
    }

    public List<String> getFields() {
        String jsonInString = new Gson().toJson(this.obj);
        JSONObject mJSONObject = new JSONObject(jsonInString);
        List<String> fields = new ArrayList<>();
        for (String key : mJSONObject.keySet()) {
            fields.add(key);
        }
        return fields;
    }

    public void delete(T obj){
        try {
            dao.delete(obj);
            successMsg();
        } catch (AppException appExc){
            appExc.printStackTrace();
            errorMsg();
        }
    }

    public void saveOrUpdate(){
        try {
            dao.saveOrUpdate((T)this.obj);
            successMsg();
        } catch (AppException appExc){
            appExc.printStackTrace();
            errorMsg();
        }
    }

    public void upload() throws IOException, AppException {
        Path folder = Paths.get("D:\\MavenProject\\PrimefacesDemo\\src\\main\\uploads");
        String filename = FilenameUtils.getBaseName(uploadedFile.getFileName());
        String extension = FilenameUtils.getExtension(uploadedFile.getFileName());
        Path file = Files.createTempFile(folder, filename + "-", "." + extension);
        try (InputStream input = uploadedFile.getInputstream()) {
            Files.copy(input, file, StandardCopyOption.REPLACE_EXISTING);
        }
        FacesMessage message = new FacesMessage("Successful", file.getFileName() + " is uploaded.");
        FacesContext.getCurrentInstance().addMessage(null, message);
        Import<Serializable> importer = new Import<Serializable>() {
            @Override
            protected Map<Integer, String> getIndexMapFieldClass() {
                Map<Integer, String> integerStringMap = new HashMap<>();
                int i = 0;
                integerStringMap.put(i++, "NAME");
                integerStringMap.put(i++, "EMAIL");
                return integerStringMap;
            }
            @Override
            protected String getDateFormat() {
                return null;
            }
        };
        String pathFile = folder.toString()+"\\"+file.getFileName();
        System.out.println(pathFile);
        System.out.println(pathFile);
        InputStream input = new FileInputStream(pathFile);
        List<Serializable> datas = importer.getDatas(input, 0, "2-");
        for(Serializable data: datas){
            System.out.println(data);
        }
        System.out.println(datas);
    }

    public void errorMsg() {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", "Có lỗi xảy ra!"));
    }

    public void successMsg() {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Thực hiện thành công!"));
    }

    public void createDynamicColumns() {
        String[] columnKeys = this.getFields().stream().toArray(String[]::new);
        columns = new ArrayList<ColumnModel>();

        for(String columnKey : columnKeys) {
            String key = columnKey.trim();
            columns.add(new ColumnModel(columnKey.toUpperCase(), columnKey));
        }
    }

    public void preEdit(BaseModel obj){
        if(obj == null) {this.obj = this.obj.build();}
        else {this.obj = obj;}
    }

    static public class ColumnModel implements Serializable {

        private String header;
        private String property;

        public ColumnModel(String header, String property) {
            this.header = header;
            this.property = property;
        }

        public String getHeader() {
            return header;
        }

        public String getProperty() {
            return property;
        }
    }
}

src/main/webapp/management/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>List of Customer</title>
</h:head>
<h:body style="padding: 60px; min-height: 2000px;">
<h:form enctype="multipart/form-data">
    <p:fileUpload mode="simple" value="#{upload.uploadedFile}" />
    <p:commandButton value="Upload" action="#{upload.upload()}" ajax="false" />
</h:form>
</h:body>
</html>

src/main/webapp/management/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>List of Customer</title>
</h:head>
<h:body style="padding: 60px; min-height: 2000px;">
    <h:form id="selectTable">
        <p:outputLabel for="@next" value="Chọn bảng cần quản lý : " />
        <p:selectOneMenu id="dropTable" >
            <p:ajax event="itemSelect" listener="#{crud.onTableChange}" update = ":customers :uploadExcel"/>
            <f:selectItem itemLabel="Chọn..." itemValue="none"/>
            <c:forEach var="table" items="${crud.allTables}">
                <f:selectItem itemLabel="#{table}" itemValue="#{table}" />
            </c:forEach>
        </p:selectOneMenu>
    </h:form>

    <br/>
    <br/>
    <br/>
    <br/>
    <h:form id = "uploadExcel" enctype="multipart/form-data">
        <p:outputPanel rendered="#{crud.showTable}">
        <p:fileUpload mode="simple" value="#{crud.uploadedFile}" />
        <p:commandButton value="Upload" action="#{crud.upload()}" ajax="false" />
        </p:outputPanel>
    </h:form>
    <h:form id="customers">


    <p:outputPanel rendered="#{crud.showTable}">
    <h1 style="margin-left: 43%;">Quản lý Khách Hàng</h1>
    <p:commandButton value="Thêm Khách hàng" style="margin-left: 46%;margin-bottom: 2%;"
                     actionListener="#{crud.preEdit(null)}"
                     oncomplete="PF('saveOrUpdateDialog').show();" update="@widgetVar(saveOrUpdateDialog)" />
    <br/>
    <br/>
    <p:dataTable paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                 rowsPerPageTemplate="5,10,15"
                 currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords} records"
                 paginator="true" rows="5" lazy="true" dynamic="true"
                 id="objList" var="obj" value="#{crud.model}">
        <p:columns value="#{crud.columns}" var="column" columnIndexVar="colIndex" sortBy="#{column.property}" filterBy="#{column.property}">
            <f:facet name="header">
                <h:outputText value="#{column.header}" />
            </f:facet>
            <h:outputText value="#{obj[column.property]}" />
        </p:columns>
        <p:column headerText="Sửa">
            <p:commandButton value="Sửa"
                             actionListener="#{crud.preEdit(obj)}"
                             oncomplete="PF('saveOrUpdateDialog').show();"
                             update="@widgetVar(saveOrUpdateDialog):panelInputInfo" />
        </p:column>
        <p:column headerText="Xoá">
            <p:commandButton update="@form objList" style="text-align:center" value="Xoá" icon="ui-icon-closethick"
                             action="#{crud.delete(obj)}"
                             styleClass="ui-priority-primary">
                <p:confirm header="Confirmation" message="Bạn có muốn xoá #{obj.name}?" icon="ui-icon-notice" />
            </p:commandButton>
            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                <p:commandButton value="Có" type="button" styleClass="ui-confirmdialog-yes" icon=" ui-icon-check" />
                <p:commandButton value="Không" type="button" styleClass="ui-confirmdialog-no" icon=" ui-icon-close" />
            </p:confirmDialog>
        </p:column>
    </p:dataTable>
    <br/>
    <p:growl id="message" showDetail="true" />
    <p:dialog header="Nhập thông tin" widgetVar="saveOrUpdateDialog" modal="true" height="220">
        <h:panelGrid columns="1" cellpadding="5" id="panelInputInfo" >
            <c:forEach var="field" items="${crud.fields}">
                <c:choose>
                    <c:when test="${field eq 'id'}">
                        <p:inputText style="display: none" value="#{crud.obj[field]}" />
                    </c:when>
                    <c:otherwise>
                        <h:outputLabel  value="#{field}:" style="font-weight:bold" />
                        <p:inputText  value="#{crud.obj[field]}" />
                    </c:otherwise>
                </c:choose>
            </c:forEach>
            <p:commandButton onclick="PF('saveOrUpdateDialog').hide()" update="@form objList" value="Lưu" icon="ui-icon-check"
                             action="#{crud.saveOrUpdate()}"
                             styleClass="ui-priority-primary">
            </p:commandButton>
        </h:panelGrid>
    </p:dialog>
    </p:outputPanel>
    </h:form>
</h:body>
</html>